name: Package CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compress
      run: make package

    - name: Upload Package Artifact
      uses: actions/upload-artifact@v4
      with:
        name: simulator-package
        path: package/code.tar.gz